points:
  key:
    padding: cy + 2

  zones:
    main:
      rows:
        bottom:
          key:
            column_net: P106
        home:
          key:
            column_net: P009
        top:
          key:
            column_net: P010
        numbers:
          key:
            column_net: P111
      columns:
        function:
          key:
            column_net: P020
        pinky:
          key:
            column_net: P022
        ring:
          key:
            origin: [-12, -19]
            stagger: 12
            column_net: P024
        middle:
          key:
            stagger: 5
            column_net: P100
        index:
          key:
            stagger: -6
            column_net: P011
        inner:
          key:
            column_net: P104
    
    thumb:
      anchor:
        ref: main_inner_bottom
        shift: [0, -25]
        rotate: -50
      rows:
      columns:
        thumb_first:
          key:
            column_net: P113
        thumb_second:
          key:
            column_net: P115
        thumb_third:
          key:
            column_net: P002
    mod:
      anchor:
        ref: thumb_thumb_first
        shift: [0, -19]
      rows:
      columns:
        thumb_first:        
          key:
            column_net: P029
        thumb_second:
          key:
            column_net: P031

outlines:
  left:
    - where: true
      what: rectangle
      size: [cx + 2, cy + 2]
      fillet: 2

pcbs:
  left:
    outlines:
      main:
        outline: left
    footprints:
      keyswitches:
        where: true
        what: choc
        params:
          hotswap: true
          from: "{{col_net}}"
          to: "{{colrow}}"
      nice_nano:
        what: nice_nano
        params:
          orientation: up
        where:
          ref: main_inner_numbers
          shift: [-9, -2]


